import React, { createContext, useContext, useState, ReactNode } from 'react';

export const translations = {
  nl: {
    nav: { results: "Resultaat", examples: "Voorbeelden", about: "Over ons", contact: "Contact", book: "Plan verkenning" },
    hero: { badge: "Klaar om AI om te zetten in echte waarde?", title1: "Iedereen praat over AI.", title2: "Maar wat betekent het voor ", title3: "úw organisatie?", desc: "U hoort de beloftes, maar mist de tijd en interne kennis om het concreet te maken. Ontdek in 15 minuten waar voor uw bedrijf de échte kansen liggen. Geen technische ruis, alleen strategische helderheid.", cta: "Plan een gratis AI-verkenning (15 min)" },
    target: { title_part1: "Klinkt dit ", title_part2: "bekend?", subtitle: "Veel MKB-organisaties worstelen met dezelfde vragen rondom de adoptie van AI.", c1: "U ziet AI overal, maar weet niet waar u moet beginnen.", c2: "Uw team experimenteert met tools, maar een echte strategie ontbreekt.", c3: "Waardevolle tijd gaat verloren aan repetitief, administratief werk.", c4: "U wilt voorkomen dat u achterloopt op concurrenten die wél innoveren." },
    social: { title: "Onafhankelijk advies over de beste AI-modellen" },
    value: { title_part1: "Van onzekerheid naar een ", title_part2: "helder actieplan.", subtitle: "Wat u direct wint door met ons in gesprek te gaan:", t1: "Krijg direct helderheid", d1: "Ontdek precies waar AI in uw specifieke processen waarde kan toevoegen en direct tijd kan besparen.", t2: "Weet wat u moet prioriteren", d2: "Voorkom keuzestress. Wij laten zien met welke simpele, eerste stap u vandaag de meeste impact maakt.", t3: "Voorkom dure fouten", d3: "Geen eindeloze IT-projecten of nutteloze tools. Wij focussen op strategische keuzes die direct renderen." },
    examples: { title_part1: "Wat kan AI concreet voor u ", title_part2: "betekenen?", subtitle: "AI hoeft niet abstract te zijn. Voor MKB-bedrijven zit de waarde vaak in zeer praktische toepassingen die direct tijd besparen.", e1: "Documenten en rapportages automatisch samenvatten.", e2: "AI-assistenten voor interne kennisdeling of klantenservice.", e3: "Repetitief administratief werk automatiseren.", e4: "Ondersteuning bij analyses, rapportages en offertes.", e5: "Grote volumes e-mails of informatie razendsnel verwerken." },
    about: { title: "Over Buuren.AI", p1: "Wij geloven dat AI geen puur technologisch vraagstuk is. Het raakt uw hele organisatie: uw processen, uw mensen, uw strategie en uw besluitvorming.", p2: "Buuren.AI is opgericht om MKB-bedrijven te helpen door de hype heen te kijken. Wij bieden geen vage beloftes of eindeloze IT-trajecten, maar pragmatische, realistische begeleiding.", p3: "Onze focus ligt op het creëren van tastbare waarde en het meenemen van uw team in de verandering." },
    faq: { title: "Veelgestelde vragen", q1: "Is de AI-verkenning echt kosteloos?", a1: "Ja, de 15-minuten verkenning is volledig gratis en vrijblijvend. Het is onze manier om te ontdekken of we waarde voor u kunnen toevoegen.", q2: "Hebben we technische kennis over AI nodig?", a2: "Absoluut niet. Wij vertalen de complexe technologie naar begrijpelijke, zakelijke oplossingen. U hoeft alleen uw eigen bedrijfsprocessen te kennen.", q3: "Is dit alleen voor grote bedrijven?", a3: "Nee, juist niet. Onze aanpak is specifiek ontworpen voor het MKB. AI biedt juist voor kleinere teams enorme kansen om efficiënter te werken.", q4: "Zitten we ergens aan vast na het gesprek?", a4: "Nee. Na het gesprek heeft u helder inzicht in uw kansen. Of u daarna met ons verder gaat, of het zelf oppakt, is helemaal aan u." },
    cta: { title: "Ontdek waar uw kansen liggen.", subtitle: "Plan een korte, vrijblijvende kennismaking. U vertelt over uw bedrijf, wij delen direct 2 tot 3 concrete AI-toepassingen die voor u relevant zijn.", f1: "Slechts 15 minuten", f2: "Kosteloos & vrijblijvend", f3: "Direct inzicht", btn: "Plan kennismaking (15 min)" },
    footer: { desc: "Onafhankelijk advies en pragmatische begeleiding bij AI-adoptie voor het MKB.", rights: "Alle rechten voorbehouden.", business: "Bedrijfsgegevens", privacy: "Privacyverklaring" },
    map: { title: "AI Kansenkaart", subtitle: "AI biedt mogelijkheden over de volledige breedte van uw organisatie.", operations: "Operaties", operationsDesc: "Procesoptimalisatie & planning", finance: "Financiën", financeDesc: "Factuurverwerking & forecasting", marketing: "Marketing", marketingDesc: "Contentcreatie & personalisatie", service: "Klantenservice", serviceDesc: "Slimme routering & concept-antwoorden", hr: "HR", hrDesc: "CV-screening & onboarding" },
    scan: { badge: "AI Opportunity Scan", title: "Ontdek waar AI waarde kan creëren in uw organisatie", subtitle: "In ongeveer 2 minuten ontdekt u waar kunstmatige intelligentie in uw organisatie de meeste impact kan maken. U ontvangt direct een aantal concrete toepassingen die relevant zijn voor uw bedrijf.", duration: "Duurt ongeveer 2 minuten", noTech: "Geen technische kennis nodig", directInsight: "Direct inzicht", start: "Start de scan", q1: "Hoe groot is uw organisatie?", q1o: ["1–10 medewerkers", "10–50 medewerkers", "50–250 medewerkers", "250+"], q2: "Waar verliest uw team momenteel het meeste tijd?", q2o: ["E-mails en communicatie", "Documenten schrijven of samenvatten", "Administratie en verwerking", "Data analyse of rapportages", "Klantenservice of vragen beantwoorden", "Marketing of content"], q3: "Gebruikt uw organisatie momenteel al AI-tools?", q3o: ["Nee", "Af en toe (bijvoorbeeld ChatGPT)", "Regelmatig", "AI is al geïntegreerd in processen"], q4: "Welke omschrijving past het beste bij uw organisatie?", q4o: ["Zakelijke dienstverlening", "Financiële dienstverlening", "Bouw / vastgoed", "IT / technologie", "Retail / e-commerce", "Overig"], q5: "Wat is uw belangrijkste doel met AI?", q5o: ["Tijd besparen", "Efficiënter werken", "Betere analyses en inzichten", "Innovatie of nieuwe diensten", "Kosten verlagen"], resultsTitle: "Uw grootste AI-kansen", resultsSubtitle: "Op basis van uw antwoorden zien we verschillende concrete mogelijkheden waar AI direct waarde kan toevoegen aan uw organisatie.", r1Title: "Document- en kennisautomatisering", r1Desc: "AI kan helpen bij het automatisch samenvatten van documenten, rapportages en interne kennis.", r2Title: "Slimme verwerking van communicatie", r2Desc: "AI kan e-mails en klantvragen analyseren, categoriseren en deels automatisch beantwoorden.", r3Title: "Automatisering van repetitieve taken", r3Desc: "Taken zoals rapportages, administratieve verwerking en analyses kunnen deels geautomatiseerd worden.", impact: "Impact", impactDesc: "Veel organisaties met een vergelijkbaar profiel besparen 20–30% tijd op repetitieve taken door AI structureel toe te passen.", ctaTitle: "Wilt u deze kansen vertalen naar uw organisatie?", ctaSubtitle: "Tijdens een kort en vrijblijvend gesprek verkennen we samen hoe deze kansen in uw specifieke situatie toegepast kunnen worden.", ctaTime: "15 minuten", ctaFree: "Kosteloos en vrijblijvend", ctaDirect: "Direct inzicht", ctaBtn: "Plan een AI-verkenning (15 min)", retry: "Scan opnieuw doen", question: "Vraag", of: "van", complete: "voltooid", next: "Volgende" }
  },
  en: {
    nav: { results: "Results", examples: "Examples", about: "About Us", contact: "Contact", book: "Book Discovery" },
    hero: { badge: "Ready to turn AI into real value?", title1: "Everyone is talking about AI.", title2: "But what does it mean for ", title3: "your business?", desc: "You hear the promises, but lack the time and internal knowledge to make them concrete. Discover where the real opportunities lie for your company in 15 minutes. No technical noise, just strategic clarity.", cta: "Book a free AI Discovery (15 min)" },
    target: { title_part1: "Does this sound ", title_part2: "familiar?", subtitle: "Many SME organizations struggle with the same questions regarding AI adoption.", c1: "You see AI everywhere, but don't know where to start.", c2: "Your team is experimenting with tools, but lacks a real strategy.", c3: "Valuable time is lost to repetitive, administrative work.", c4: "You want to avoid falling behind competitors who are innovating." },
    social: { title: "Independent advice on the best AI models" },
    value: { title_part1: "From uncertainty to a ", title_part2: "clear action plan.", subtitle: "What you gain immediately by talking to us:", t1: "Get immediate clarity", d1: "Discover exactly where AI can add value and save time directly in your specific processes.", t2: "Know what to prioritize", d2: "Avoid choice paralysis. We show you the simple first step that makes the most impact today.", t3: "Avoid costly mistakes", d3: "No endless IT projects or useless tools. We focus on strategic choices that yield immediate returns." },
    examples: { title_part1: "What can AI concretely ", title_part2: "do for you?", subtitle: "AI doesn't have to be abstract. For SMEs, value is often found in very practical applications that save time immediately.", e1: "Automatically summarizing documents and reports.", e2: "AI assistants for internal knowledge sharing or customer service.", e3: "Automating repetitive administrative work.", e4: "Support with analysis, reporting, and proposals.", e5: "Processing large volumes of emails or information at lightning speed." },
    about: { title: "About Buuren.AI", p1: "We believe that AI is not purely a technological issue. It affects your entire organization: your processes, your people, your strategy, and your decision-making.", p2: "Buuren.AI was founded to help SMEs see through the hype. We don't offer vague promises or endless IT projects, but pragmatic, realistic guidance.", p3: "Our focus is on creating tangible value and guiding your team through the change." },
    faq: { title: "Frequently Asked Questions", q1: "Is the AI Discovery really free?", a1: "Yes, the 15-minute discovery call is completely free and without obligation. It's our way of finding out if we can add value for you.", q2: "Do we need technical knowledge about AI?", a2: "Absolutely not. We translate complex technology into understandable business solutions. You only need to know your own business processes.", q3: "Is this only for large companies?", a3: "No, quite the opposite. Our approach is specifically designed for SMEs. AI offers enormous opportunities for smaller teams to work more efficiently.", q4: "Are we tied to anything after the call?", a4: "No. After the call, you will have a clear understanding of your opportunities. Whether you choose to proceed with us or handle it yourself is entirely up to you." },
    cta: { title: "Discover where your opportunities lie.", subtitle: "Schedule a short, complimentary consultation. Tell us about your company, and we'll immediately share 2 to 3 practical AI applications relevant to you.", f1: "Only 15 minutes", f2: "Free & no obligation", f3: "Direct insights", btn: "Schedule Consultation (15 min)" },
    footer: { desc: "Independent advice and pragmatic guidance for AI adoption in SMEs.", rights: "All rights reserved.", business: "Business details", privacy: "Privacy policy" },
    map: { title: "AI Opportunity Map", subtitle: "AI offers opportunities across the full breadth of your organization.", operations: "Operations", operationsDesc: "Process optimization & planning", finance: "Finance", financeDesc: "Invoice processing & forecasting", marketing: "Marketing", marketingDesc: "Content creation & personalization", service: "Customer Service", serviceDesc: "Smart routing & draft responses", hr: "HR", hrDesc: "CV screening & onboarding" },
    scan: { badge: "AI Opportunity Scan", title: "Discover where AI can create value in your organization", subtitle: "In about 2 minutes, discover where artificial intelligence can make the biggest impact in your organization. You'll immediately receive concrete applications relevant to your business.", duration: "Takes about 2 minutes", noTech: "No technical knowledge needed", directInsight: "Direct insight", start: "Start the scan", q1: "How large is your organization?", q1o: ["1–10 employees", "10–50 employees", "50–250 employees", "250+"], q2: "Where does your team currently lose the most time?", q2o: ["Emails and communication", "Writing or summarizing documents", "Administration and processing", "Data analysis or reporting", "Customer service or answering questions", "Marketing or content"], q3: "Does your organization currently use AI tools?", q3o: ["No", "Occasionally (e.g. ChatGPT)", "Regularly", "AI is already integrated into processes"], q4: "Which description best fits your organization?", q4o: ["Business services", "Financial services", "Construction / real estate", "IT / technology", "Retail / e-commerce", "Other"], q5: "What is your main goal with AI?", q5o: ["Save time", "Work more efficiently", "Better analyses and insights", "Innovation or new services", "Reduce costs"], resultsTitle: "Your biggest AI opportunities", resultsSubtitle: "Based on your answers, we see several concrete possibilities where AI can directly add value to your organization.", r1Title: "Document & knowledge automation", r1Desc: "AI can help automatically summarize documents, reports, and internal knowledge.", r2Title: "Smart communication processing", r2Desc: "AI can analyze, categorize, and partially auto-respond to emails and customer inquiries.", r3Title: "Automation of repetitive tasks", r3Desc: "Tasks such as reports, administrative processing, and analyses can be partially automated.", impact: "Impact", impactDesc: "Many organizations with a similar profile save 20-30% of time on repetitive tasks by applying AI structurally.", ctaTitle: "Want to translate these opportunities to your organization?", ctaSubtitle: "During a short, no-obligation conversation, we'll explore together how these opportunities can be applied in your specific situation.", ctaTime: "15 minutes", ctaFree: "Free & no obligation", ctaDirect: "Direct insight", ctaBtn: "Schedule an AI Discovery (15 min)", retry: "Retake the scan", question: "Question", of: "of", complete: "complete", next: "Next" }
  }
};

type Language = 'nl' | 'en';

type LanguageContextType = {
  t: typeof translations.nl;
  language: Language;
  setLanguage: (lang: Language) => void;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('nl');

  return (
    <LanguageContext.Provider value={{ t: translations[language], language, setLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
